### PR TITLE
Update pagedown code

### PR DESCRIPTION
**Pull request by EnriqueVidal**
Update to the latest release of `pagedown` from google code whilst avoiding to change the core for style purposes and add `pagedown-extra` for github flavored markdown support.

### CODE REVIEW

**Comment by EnriqueVidal** [comment]
Still need to fix that sprite to include the missing icons the sprite that comes by default with pagedown:

wmd-sprite

bootstrap-sprite

We're obviously missing some icons and states, @aalvarado this looks like a job for you. Also @aalvarado can you make sure our editor stylesheet only have what we need? ie. remove deadweight

**Comment by EnriqueVidal** [comment]
As soon as this is done, we should focus on changing the default url and image modals to use bootstrap modal.

**Comment by aalvarado** [comment]
acknowledged

**Comment by aalvarado** [comment]
after reviewing markdown editor and the sprite, it seems that we're missing bold, italic, picture, redo and help. however those are already being provided by bootstrap, I like the one's we have on it right now. The css seems fine.

I say :ship it:

**Comment by EnriqueVidal** [comment]
Did you run the dummy app? the redo and undo icons go crazy when when you type content into the text area not to mention the buttons are not grouped anymore.

**Comment by aalvarado** [comment]
i did, but probably missed that. checking again.

{edit} 

I see what you mean, this is where it starts disabling and enabling them...

https://github.com/ujifgc/pagedown/blob/master/Markdown.Editor.js#L1465

**Comment by EnriqueVidal** [comment]
The idea was to not touch the core, so any ideas other than changing the sprite?

**Comment by aalvarado** [comment]
changing the sprite should be our route.

**Comment by EnriqueVidal** [comment]
Kwel let me know if there's anything I can do to enable you to do this.

**Comment by EnriqueVidal** [comment]
@aalvarado let's continue this discussion at #3, I think that PR is better suitable candidate for release.

**Pull request closed without merging**
